service: clash-update-hostedzone
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: python3.6
  region: us-east-1
  timeout: 15
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:DescribeNetworkInterfaces"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "route53:ChangeResourceRecordSets"
        - "route53:ListResourceRecordSets"
      Resource:
      - "*"

functions:
  hello:
    handler: handler.update
    events:
      - schedule: rate(5 minutes)
